apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: events-identity-binding  # Name of the Azure Identity Binding.
  namespace: default             # Namespace where the binding is applied.
spec:
  azureIdentity: events-identity # Name of the Azure Identity resource to bind.
  selector: events-identity      # Pod label selector to associate with this Azure Identity Binding.
