apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: events-identity-binding
  namespace: default
spec:
  azureIdentity: events-identity
  selector: events-identity
