apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: receive-events-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: receive-events-deployment  # Name of the target deployment
  pollingInterval: 30               # Check metrics every 30 seconds
  cooldownPeriod: 300               # Wait for 5 minutes before scaling down
  minReplicaCount: 1                # Minimum number of pods
  maxReplicaCount: 10               # Maximum number of pods
  triggers:
    - type: azure-eventhub
      metadata:
        eventHubNamespace: <event-hub-namespace>
        eventHubName: <event-hub-name>
        consumerGroup: "$Default"
        threshold: "200"                                 # Messages threshold for scaling      
        storageAccountName: <storage-account-name>
        blobContainer: <blob-container-name>
      authenticationRef:
        name: receive-events-auth
