apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: receive-events-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: receive-events-deployment  # Name of the target deployment to scale.
  pollingInterval: 30               # Check metrics every 30 seconds.
  cooldownPeriod: 300               # Wait for 5 minutes before scaling down.
  minReplicaCount: 1                # Minimum number of pods.
  maxReplicaCount: 10               # Maximum number of pods.
  triggers:
    - type: azure-eventhub
      metadata:
        eventHubNamespace: <event-hub-namespace> # Replace <event-hub-namespace> with the name of your Event Hub namespace.
        eventHubName: <event-hub-name>           # Replace <event-hub-name> with the name of your Event Hub.
        consumerGroup: "$Default"               # Consumer group used for the Event Hub.
        threshold: "200"                        # Messages threshold for scaling.
        storageAccountName: <storage-account-name> # Replace <storage-account-name> with the name of your Azure Storage account for checkpointing.
        blobContainer: <blob-container-name>        # Replace <blob-container-name> with the name of your blob container for checkpointing.
      authenticationRef:
        name: receive-events-auth              # Reference to the TriggerAuthentication resource.
