apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: receive-events-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: receive-events-deployment  # Name of the target deployment
  pollingInterval: 30               # Check metrics every 30 seconds
  cooldownPeriod: 300               # Wait for 5 minutes before scaling down
  minReplicaCount: 1                # Minimum number of pods
  maxReplicaCount: 10               # Maximum number of pods
  triggers:
    - type: azure-eventhub
      metadata:
        eventHubNamespace: lab2-phx-eh       # Event Hub namespace
        eventHubName: lab2-phx-eh-eh         # Event Hub name
        consumerGroup: "$Default"            # Consumer group (default is "$Default")
        threshold: "200"                     # Messages threshold for scaling
        storageAccountName: phxlab2sa        # Storage account name for checkpointing
        blobContainer: lab2blobeh            # Blob container name for checkpointing
      authenticationRef:
        name: receive-events-auth            # Reference to the authentication secret
