apiVersion: apps/v1
kind: Deployment
metadata:
  name: receive-events-deployment
  labels:
    app: receive-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receive-events
  template:
    metadata:
      labels:
        app: receive-events
      annotations:
        aadpodidentitybinding: receive-events-binding
    spec:
      containers:
      - name: receive-events
        image: phxlab2cr.azurecr.io/receive-events:latest
        ports:
        - containerPort: 80
        env:
        - name: EVENT_HUB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: event-hub-credentials
              key: EVENT_HUB_CONNECTION_STRING
        - name: EVENT_HUB_NAME
          valueFrom:
            secretKeyRef:
              name: event-hub-credentials
              key: EVENT_HUB_NAME
