apiVersion: apps/v1
kind: Deployment
metadata:
  name: receive-events-deployment
  labels:
    app: receive-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receive-events
  template:
    metadata:
      labels:
        app: receive-events
        aadpodidbinding: events-identity
    spec:
      containers:
      - name: receive-events
        image: <container-registry>/receive-events:latest
        ports:
        - containerPort: 80
        env:
        - name: EVENT_HUB_NAMESPACE
          value: <event-hub-namespace>
        - name: EVENT_HUB_NAME
          value: <event-hub-name>
        - name: CONSUMER_GROUP
          value: "$Default"
