apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-events-deployment
  labels:
    app: send-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-events
  template:
    metadata:
      labels:
        app: send-events
        aadpodidbinding: events-identity
    spec:
      containers:
      - name: send-events
        image: <container-registry>/send-events:latest
        ports:
        - containerPort: 80
        env:
        - name: EVENT_HUB_NAMESPACE
          value: <event-hub-namespace>
        - name: EVENT_HUB_NAME
          value: <event-hub-name>
        - name: EVENT_SEND_DELAY
          value: "5"
