apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-events-deployment
  labels:
    app: send-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-events
  template:
    metadata:
      labels:
        app: send-events
      annotations:
        aadpodidentitybinding: send-events-binding
    spec:
      containers:
      - name: send-events
        image: phxlab2cr.azurecr.io/send-events:latest
        ports:
        - containerPort: 80
        env:
        - name: EVENT_HUB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: event-hub-credentials
              key: EVENT_HUB_CONNECTION_STRING
        - name: EVENT_HUB_NAME
          valueFrom:
            secretKeyRef:
              name: event-hub-credentials
              key: EVENT_HUB_NAME
