apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-events-deployment  # Name of the deployment.
  labels:
    app: send-events            # Label to identify the app.
spec:
  replicas: 1                   # Number of pod replicas.
  selector:
    matchLabels:
      app: send-events          # Selector to match the pod labels.
  template:
    metadata:
      labels:
        app: send-events        # Label for the pod.
        aadpodidbinding: events-identity # Name of the Azure Identity binding for the pod.
    spec:
      containers:
      - name: send-events       # Name of the container.
        image: <container-registry>/send-events:latest # Replace <container-registry> with the name of your Azure Container Registry.
        ports:
        - containerPort: 80     # Port exposed by the container.
        env:
        - name: EVENT_HUB_NAMESPACE
          value: <event-hub-namespace> # Replace <event-hub-namespace> with the name of your Event Hub namespace.
        - name: EVENT_HUB_NAME
          value: <event-hub-name>       # Replace <event-hub-name> with the name of your Event Hub.
        - name: EVENT_SEND_DELAY
          value: "5"                    # Delay between sending events (in seconds).
