apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: receive-events-auth
  namespace: default
spec:
  podIdentity:
    identityId: <client-id>
    provider: azure-workload
